export const automotiveSolutions = [
  {
    slug: "passenger-vehicle-solutions",
    menuLabel: "Passenger vehicle solutions",
    title: "Passenger Vehicle Solutions",
    eyebrow: "01 / Everyday mobility",
    introduction: "A considered approach to vehicle care, fluid selection and reliable maintenance, built around the needs of modern passenger vehicles.",
    heroImage: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Modern passenger car on a road",
    overviewTitle: "Confidence for every kind of journey.",
    overview: "From daily commutes to long-distance travel, vehicles depend on products that suit their design, driving conditions and service schedule. NEXBLUE brings these needs together in a clear, practical solution for owners, workshops and automotive partners.",
    workflow: {
      title: "A care cycle that starts with the vehicle",
      introduction: "Connect product choices to the car's service history, how it is driven and the next planned visit.",
      steps: [
        { title: "Identify the vehicle", copy: "Confirm model, year, powertrain and the exact system being serviced before looking up a product requirement." },
        { title: "Set the service baseline", copy: "Use the owner's manual and service record to establish the applicable specification and maintenance interval." },
        { title: "Carry the record forward", copy: "Note products used, work completed and the next due service so future visits start with useful context." },
      ],
    },
    areas: [
      { title: "Powertrain care", copy: "Engine and drivetrain products selected around vehicle requirements and manufacturer guidance.", details: "Check the vehicle handbook for the required specification and viscosity. Confirm the application before service, and record the product used for future maintenance." },
      { title: "Routine maintenance", copy: "Service essentials that help workshops deliver consistent care at every scheduled visit.", details: "Build each service visit around the prescribed maintenance schedule. Pair fluid checks and replacement tasks with a documented inspection of related systems." },
      { title: "Vehicle protection", copy: "Cleaning and protection options that support a well-maintained cabin and exterior.", details: "Select cleaners and protectants for the surface being treated. Follow label directions, test sensitive materials where appropriate, and avoid applying products outside their intended use." },
      { title: "Reliable replenishment", copy: "Coordinated product availability for service centres, retailers and multi-vehicle customers.", details: "Use service volume and reorder history to define a practical core assortment. Review slow-moving lines regularly while protecting availability of frequently used items." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Passenger vehicle engine during a service" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Technician performing routine vehicle maintenance" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Passenger vehicle prepared for everyday driving" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Passenger car supported by a vehicle care program" },
    ],
    applications: ["Personal vehicles", "Multi-vehicle households", "Independent service centres", "Automotive retail"],
    supportTitle: "A better ownership experience, thoughtfully supported.",
    supportCopy: "We help partners bring products, product guidance and dependable supply together, making vehicle care easier to plan and simpler to deliver.",
    supportImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Passenger vehicle ready for a drive",
  },
  {
    slug: "commercial-vehicle-solutions",
    menuLabel: "Commercial vehicle solutions",
    title: "Commercial Vehicle Solutions",
    eyebrow: "02 / Work in motion",
    introduction: "Practical product and supply programs for commercial vehicles that keep people, goods and essential services moving.",
    heroImage: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Commercial vehicle travelling on an open road",
    overviewTitle: "Support built around vehicles that earn their keep.",
    overview: "Commercial vehicles operate across demanding routes, schedules and service environments. NEXBLUE helps operators and service partners bring the right maintenance products and replenishment approach together for the work each vehicle performs.",
    workflow: {
      title: "Turn fleet information into a service rhythm",
      introduction: "Bring vehicle mix, route demands and maintenance access together in one repeatable operating plan.",
      steps: [
        { title: "Segment the fleet", copy: "Group vehicles by type, specification and role so service needs are not averaged across unlike assets." },
        { title: "Map the duty", copy: "Record route length, payload patterns, idle time and operating locations that affect service planning." },
        { title: "Reserve service windows", copy: "Coordinate planned inspections with dispatch and return schedules to make maintenance time visible." },
        { title: "Replenish against use", copy: "Use product issue history and supplier lead time to plan restocking across depots." },
      ],
    },
    areas: [
      { title: "Duty-aware maintenance", copy: "Fluid and service essentials organized around vehicle use, operating conditions and maintenance plans.", details: "Group vehicles by type, load profile and route conditions. Use each vehicle maker's service guidance as the baseline, then plan inspections around actual operating schedules." },
      { title: "Uptime-minded supply", copy: "Planned replenishment options that help reduce last-minute sourcing across operating locations.", details: "Identify critical products, lead times and delivery points across the fleet. Set reorder triggers that account for usage and replenishment time rather than relying on emergency requests." },
      { title: "Workshop coordination", copy: "A consistent product approach for in-house teams, service partners and distributed fleets.", details: "Align approved product lists and service expectations between internal workshops and external providers. Keep substitutions visible and confirm compatibility before use." },
      { title: "Clear product guidance", copy: "Straightforward selection support to help teams align products with vehicle specifications.", details: "Give technicians and procurement teams access to vehicle-specific requirements, product documentation and clear identification to reduce selection ambiguity." },
      { title: "Route-ready replenishment", copy: "Supply routines matched to service windows, delivery schedules and operating locations.", details: "Coordinate deliveries around depot access, vehicle return times and planned service windows. Adjust frequency for route seasonality and changes in fleet activity." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Commercial vehicle traveling on a road" },
      { url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=82", alt: "Commercial transport truck on a highway" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Commercial vehicle undergoing workshop maintenance" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Vehicle components inspected for service" },
      { url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=82", alt: "Fleet vehicle ready for its next route" },
    ],
    applications: ["Delivery fleets", "Passenger transport", "Service vehicles", "Commercial workshops"],
    supportTitle: "Keep operational needs connected to maintenance.",
    supportCopy: "From product selection to supply planning, we work with fleet and service teams to make everyday vehicle support more predictable.",
    supportImage: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Commercial transport truck on a highway",
  },
  {
    slug: "heavy-vehicle-solutions",
    menuLabel: "Heavy vehicle solutions",
    title: "Heavy Vehicle Solutions",
    eyebrow: "03 / Built for demanding duty",
    introduction: "Maintenance and fluid support for heavy vehicles working through long hours, challenging routes and demanding loads.",
    heroImage: "https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Heavy-duty truck operating on a road",
    overviewTitle: "Dependable support for demanding operations.",
    overview: "Heavy vehicles need maintenance programs that reflect how equipment is used, where it operates and how service is delivered. We help connect suitable products, selection guidance and supply planning across the vehicle lifecycle.",
    workflow: {
      title: "Plan service around equipment duty",
      introduction: "For heavy equipment, a useful plan links machine specifications with site conditions and service records.",
      steps: [
        { title: "Document the asset", copy: "Capture model, engine or system details, attachments and the applicable service documentation." },
        { title: "Review site conditions", copy: "Include operating hours, load, temperature, dust, terrain and access to maintenance facilities." },
        { title: "Stage approved essentials", copy: "Plan product availability and safe storage around planned service work and site constraints." },
        { title: "Track hours and work", copy: "Record meter readings, inspections and products used to inform the next maintenance interval." },
      ],
    },
    areas: [
      { title: "Heavy-duty fluid programs", copy: "Product planning for engine, transmission and hydraulic requirements, guided by equipment specifications.", details: "Map each machine to its manufacturer-approved requirements. Keep application records clear across engine, transmission and hydraulic systems, and do not infer interchangeability between products." },
      { title: "Service interval support", copy: "Maintenance essentials organized to support planned inspections and scheduled work.", details: "Translate operating hours and scheduled service guidance into inspection and replenishment checkpoints. Record completed work so intervals remain traceable across shifts and sites." },
      { title: "Remote-site readiness", copy: "Supply coordination for operations where access, timing and stock visibility matter.", details: "Identify minimum on-site stocks for critical service needs, then plan deliveries around access constraints and expected consumption. Include safe storage and inventory checks in site routines." },
      { title: "Equipment continuity", copy: "Consistent service products across mixed vehicle types and operating locations.", details: "Standardize where specifications permit, while retaining equipment-specific product records. Make approved product lists available to operators, maintenance teams and supply partners." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=900&q=82", alt: "Heavy-duty vehicle operating under load" },
      { url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=82", alt: "Heavy transport vehicle on a highway" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Commercial vehicle working across a route" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Mechanical components prepared for heavy vehicle service" },
    ],
    applications: ["Long-haul transport", "Construction equipment", "Mining support vehicles", "Public works fleets"],
    supportTitle: "Built around the work, not just the vehicle.",
    supportCopy: "We work with operators and service teams to align fluid selection, maintenance routines and supply with real operating conditions.",
    supportImage: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Heavy transport vehicle in operation",
  },
  {
    slug: "automotive-maintenance-products",
    menuLabel: "Automotive maintenance products",
    title: "Automotive Maintenance Products",
    eyebrow: "04 / Care through every service",
    introduction: "A practical range of maintenance essentials to help service teams care for vehicles consistently, from routine checks to planned repairs.",
    heroImage: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Automotive engine components during maintenance",
    overviewTitle: "The right essentials for a well-run service bay.",
    overview: "Good maintenance depends on sound procedures and dependable products. NEXBLUE helps service teams organize the everyday products used to inspect, clean, lubricate and maintain vehicles, with selection grounded in vehicle and product guidance.",
    workflow: {
      title: "Organize maintenance around the job order",
      introduction: "Make product selection part of a clear service sequence, from the first inspection to the final record.",
      steps: [
        { title: "Inspect and define the job", copy: "Use the service request and vehicle assessment to distinguish required work from optional recommendations." },
        { title: "Prepare the product list", copy: "Match fluids, cleaners and consumables to the vehicle specification and the approved repair procedure." },
        { title: "Complete work with traceability", copy: "Record products used and follow handling instructions during servicing, cleaning and top-ups." },
        { title: "Close out and replenish", copy: "Confirm the completed work with the customer and return unopened stock to its identified location." },
      ],
    },
    areas: [
      { title: "Service fluids", copy: "Vehicle-care fluids selected to suit the application and recommended service requirements.", details: "Confirm the vehicle and system specification before selection. Keep product labels and technical documentation available at the point of use, and record top-ups or replacements." },
      { title: "Cleaning and preparation", copy: "Workshop cleaning products for service work, components and work areas.", details: "Choose cleaning chemistry for the soil, component and surface involved. Follow dilution, contact-time and protective-equipment instructions on the product label." },
      { title: "Repair essentials", copy: "Frequently used consumables organized to support routine maintenance and repair tasks.", details: "Review common repair jobs to identify the consumables technicians need together. Store them close to relevant work areas and distinguish general-use items from application-specific materials." },
      { title: "Stock planning", copy: "A clearer view of everyday product needs to support availability and reduce avoidable gaps.", details: "Track issue quantities and supplier lead times by product. Use those records to establish reorder points and periodically remove obsolete or rarely used stock." },
      { title: "Inspection and top-ups", copy: "A repeatable approach to checking service items and addressing routine fluid needs.", details: "Include fluid level and condition checks in the relevant service workflow. Top up only with a product meeting the required specification, and investigate recurring losses rather than masking them." },
      { title: "Workshop handling", copy: "Practical product organization to support careful storage, use and replenishment.", details: "Keep containers closed, identifiable and stored according to label guidance. Separate products where contamination or accidental mixing could affect service quality." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Automotive parts being inspected during maintenance" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Vehicle cleaning and preparation in a workshop" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Passenger vehicle supported by maintenance products" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle checked before returning to the road" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Vehicle service supporting day-to-day use" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Automotive service products and components" },
    ],
    applications: ["Scheduled servicing", "Preventive maintenance", "Mechanical repairs", "Service preparation"],
    supportTitle: "Maintenance products with clear purpose.",
    supportCopy: "We help teams simplify product selection and replenishment, so technicians can focus on consistent, careful work.",
    supportImage: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Technician carrying out vehicle maintenance in a workshop",
  },
  {
    slug: "workshop-solutions",
    menuLabel: "Workshop solutions",
    title: "Workshop Solutions",
    eyebrow: "05 / Ready for the next job",
    introduction: "Product programs and replenishment support that help workshops stay organized, service-ready and focused on their customers.",
    heroImage: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Well-equipped automotive service workshop",
    overviewTitle: "A more connected way to run workshop essentials.",
    overview: "Workshops balance customer bookings, technician time and a changing list of product needs. NEXBLUE brings common consumables, maintenance products and supply coordination into a straightforward framework that can adapt to each service operation.",
    workflow: {
      title: "From service menu to ready bay",
      introduction: "Translate the work a workshop accepts into a practical system for staging products and replenishing stock.",
      steps: [
        { title: "Map the service mix", copy: "List common maintenance, repair, cleaning and preparation jobs, then identify their recurring product needs." },
        { title: "Build bay-ready assortments", copy: "Place frequently used products near their point of use while keeping specialist items clearly identified." },
        { title: "Set the delivery cadence", copy: "Agree ordering cut-offs and delivery days around bookings, storage capacity and supplier lead times." },
        { title: "Review what actually moves", copy: "Check usage, stock-outs and unused lines regularly; adjust the assortment as the workshop mix changes." },
      ],
    },
    areas: [
      { title: "Workshop assortments", copy: "A considered mix of everyday products organized around the services your team provides.", details: "Build the assortment from the workshop's service menu: scheduled maintenance, diagnostics, repair, cleaning or preparation. Remove products that do not support the actual work mix." },
      { title: "Usage-led replenishment", copy: "Supply planning informed by workshop routines, service volume and storage constraints.", details: "Compare product issues against service volume and delivery lead time. Set replenishment thresholds that fit available storage and review them when seasonal demand changes." },
      { title: "Service-bay readiness", copy: "Product availability that helps teams prepare for routine jobs and scheduled work.", details: "Use job preparation lists to stage the correct products before a booking enters the bay. Return unused items to identified storage and update stock records after work is complete." },
      { title: "Partner coordination", copy: "A dependable point of connection for workshops, suppliers and service networks.", details: "Agree on order cut-offs, delivery expectations, escalation contacts and product-substitution approvals with each supply partner." },
      { title: "Safe storage practices", copy: "Product organization and handling guidance suited to the workshop environment.", details: "Keep products labeled and stored under their stated conditions. Maintain separation for incompatible materials and ensure staff can find relevant handling information." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Automotive workshop prepared for a service job" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Technician working with automotive components" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Vehicle being prepared for service" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Vehicle service customer collection" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle ready after workshop service" },
    ],
    applications: ["Independent garages", "Authorized service networks", "Multi-bay workshops", "Mobile service teams"],
    supportTitle: "Less time sourcing. More time serving.",
    supportCopy: "We help workshops build a practical essentials program around their service mix and the way their teams actually work.",
    supportImage: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Automotive service equipment inside a workshop",
  },
  {
    slug: "automotive-consumables",
    menuLabel: "Automotive consumables",
    title: "Automotive Consumables",
    eyebrow: "06 / Everyday essentials",
    introduction: "The frequently used products behind efficient vehicle care, workshop preparation and dependable service delivery.",
    heroImage: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Automotive service tools and supplies",
    overviewTitle: "Small essentials. A meaningful difference.",
    overview: "Consumables are easy to overlook until they are missing. A thoughtful assortment and replenishment routine helps service teams keep work moving while maintaining clear control of frequently used products.",
    workflow: {
      title: "Build a core assortment that earns its shelf space",
      introduction: "A strong consumables program starts with real workshop usage, not a catalogue filled with every possible item.",
      steps: [
        { title: "List by task", copy: "Connect wipes, gloves, cleaners and other supplies to the jobs that use them and the teams responsible." },
        { title: "Separate core from occasional", copy: "Protect availability for fast-moving essentials while sourcing specialist items to match actual demand." },
        { title: "Make replenishment visible", copy: "Use clear locations, pack units and reorder signals so low stock is noticed before the next job." },
      ],
    },
    areas: [
      { title: "Frequently used supplies", copy: "A structured view of the products teams reach for across everyday service work.", details: "Classify supplies by how often they are used and which jobs consume them. Keep fast-moving essentials visible in stock checks and separate them from occasional-use items." },
      { title: "Clean and protect", copy: "Care items that support tidy work areas and considerate vehicle handling.", details: "Distinguish products for vehicle surfaces from those intended for workshop floors, tools or components. Follow surface compatibility and handling directions for each use." },
      { title: "Workshop organization", copy: "Practical assortment planning to make storage and stock checks easier.", details: "Use consistent product names, storage locations and reorder units. A simple location map helps teams return supplies correctly and spot low stock during routine checks." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Automotive workshop consumables organized for service" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Automotive supplies used during vehicle care" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle care products supporting preparation" },
    ],
    applications: ["Service workshops", "Vehicle preparation", "Dealership operations", "Fleet maintenance teams"],
    supportTitle: "Keep everyday work moving smoothly.",
    supportCopy: "NEXBLUE helps bring common consumables into one understandable, service-focused supply plan.",
    supportImage: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Vehicle components prepared for maintenance work",
  },
  {
    slug: "vehicle-operating-fluids",
    menuLabel: "Vehicle operating fluids",
    title: "Vehicle Operating Fluids",
    eyebrow: "07 / Performance in balance",
    introduction: "Fluid solutions and selection support for the systems that help vehicles operate smoothly across changing conditions.",
    heroImage: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Modern vehicle reflecting careful engineering",
    overviewTitle: "Fluid choices guided by the vehicle.",
    overview: "Vehicle fluids serve different functions and must match the system, specification and service conditions. Our approach starts with the application, helping customers and service partners navigate product needs with clarity rather than guesswork.",
    workflow: {
      title: "Trace every fluid from specification to service",
      introduction: "A disciplined selection path helps teams avoid confusion between products that serve different vehicle systems.",
      steps: [
        { title: "Identify the system", copy: "Confirm whether the requirement relates to lubrication, cooling, transmission or another vehicle application." },
        { title: "Verify the requirement", copy: "Check the vehicle documentation for the exact specification before selecting or topping up a fluid." },
        { title: "Protect product integrity", copy: "Keep containers labeled, closed and stored as directed; use clean equipment during transfer." },
        { title: "Record the service", copy: "Document the product and work completed so the next technician has an accurate reference." },
      ],
    },
    areas: [
      { title: "Application-led selection", copy: "Product guidance that starts with vehicle requirements and the relevant manufacturer recommendations.", details: "Identify vehicle year, model, engine or system, then confirm the required performance specification in its service documentation before choosing a product." },
      { title: "System-specific support", copy: "A clear distinction between lubrication, cooling, transmission and other fluid applications.", details: "Keep separate records for each fluid system and its approved requirements. Similar appearance or purpose does not establish compatibility between products." },
      { title: "Service partner access", copy: "Product availability and information organized for workshops and automotive channels.", details: "Provide service teams with current product identification and technical documents. Make the information easy to access at the counter, in the bay and during replenishment." },
      { title: "Responsible handling", copy: "Practical support for storage, identification and appropriate product use.", details: "Follow container instructions for storage and handling, keep labels legible, and use clean equipment to avoid contaminating products during transfer." },
      { title: "Compatibility and storage", copy: "Guidance to help teams keep products identified, stored and matched to the right system.", details: "Rotate inventory using receipt dates and inspect containers before use. Store products in designated areas and do not combine leftovers unless the product guidance allows it." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Vehicle operating systems inspected during service" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Technician servicing vehicle fluid systems" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle prepared for dependable operation" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Passenger vehicle for fluid application planning" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Commercial vehicle supported by operating fluids" },
    ],
    applications: ["Passenger vehicles", "Commercial vehicles", "Workshop servicing", "Automotive distribution"],
    supportTitle: "Clarity from specification to service.",
    supportCopy: "We help partners connect product requirements with practical selection and dependable access across the service journey.",
    supportImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Vehicle on a road representing dependable operation",
  },
  {
    slug: "dealership-service-centre-solutions",
    menuLabel: "Dealership and service-centre solutions",
    title: "Dealership & Service-Centre Solutions",
    eyebrow: "08 / Every visit, well supported",
    introduction: "Connected product and service support for dealership and service-centre teams, from vehicle intake through customer handover.",
    heroImage: "https://images.unsplash.com/photo-1562519819-016930ada31b?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Contemporary vehicle retail and service environment",
    overviewTitle: "A consistent experience across every service point.",
    overview: "Dealerships and service centres bring together customer care, workshop execution and parts or product availability. NEXBLUE helps teams coordinate maintenance products and consumables in a way that supports a consistent, considered service experience.",
    workflow: {
      title: "Create a repeatable service-centre journey",
      introduction: "Connect the customer promise with workshop preparation and a clear handover at every branch.",
      steps: [
        { title: "Set expectations at booking", copy: "Capture the vehicle, requested work and applicable service plan before the visit begins." },
        { title: "Prepare the bay", copy: "Stage the required products and share the job information with the assigned service team." },
        { title: "Keep branches aligned", copy: "Use shared product references and service practices while tracking approved local variations." },
        { title: "Close the loop", copy: "Record completed work and product use, then explain the service outcome at customer handover." },
      ],
    },
    areas: [
      { title: "Service menu support", copy: "Product planning aligned to scheduled maintenance and common service operations.", details: "Map products to the services listed in the dealership menu, from routine visits to seasonal checks. Keep the approved product reference close to booking and workshop teams." },
      { title: "Multi-site consistency", copy: "A coherent approach to everyday products across branches and service locations.", details: "Use common product identifiers and service guidance across sites, while recording local exceptions and authorized alternatives." },
      { title: "Customer-ready care", copy: "Vehicle care products and processes that support thoughtful preparation and handover.", details: "Define preparation steps for each vehicle handover type. Choose products appropriate to the material and follow directions to avoid residue or surface damage." },
      { title: "Supply coordination", copy: "Clearer ordering and replenishment communication between teams and locations.", details: "Set shared order calendars and escalation paths for branches. Review local demand with central procurement before changing the approved range." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1562519819-016930ada31b?auto=format&fit=crop&w=900&q=82", alt: "Modern dealership and vehicle service environment" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Service-centre technician preparing a vehicle" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Vehicle ready for dealership service" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle prepared for customer handover" },
    ],
    applications: ["Authorized dealerships", "Service-centre groups", "Vehicle preparation teams", "Customer care operations"],
    supportTitle: "Make every touchpoint feel considered.",
    supportCopy: "We work with dealership teams to simplify product programs and create reliable support from service booking to vehicle return.",
    supportImage: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Service team working on a vehicle in a clean workshop",
  },
  {
    slug: "institutional-automotive-supply",
    menuLabel: "Institutional automotive supply",
    title: "Institutional Automotive Supply",
    eyebrow: "09 / Supply at operational scale",
    introduction: "Structured automotive product supply for institutions managing vehicles, service locations and procurement requirements at scale.",
    heroImage: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Organized commercial vehicle fleet",
    overviewTitle: "A supply framework built for multiple stakeholders.",
    overview: "Institutional supply brings together procurement policy, operating locations, approved products and ongoing demand. NEXBLUE helps create a practical framework for product standardization, ordering visibility and coordinated delivery.",
    workflow: {
      title: "Build a procurement-to-delivery program",
      introduction: "Make product approvals, orders and site-level receipt part of one accountable supply process.",
      steps: [
        { title: "Define approved requirements", copy: "Document intended applications, technical specifications and any permitted alternatives." },
        { title: "Consolidate demand", copy: "Collect expected usage across departments and locations, including delivery access and storage limits." },
        { title: "Set ordering controls", copy: "Clarify who can request, approve and place orders, and which records must accompany each order." },
        { title: "Allocate and acknowledge", copy: "Track dispatch, receipt and distribution to operating sites against the original request." },
        { title: "Reconcile the program", copy: "Review consumption, exceptions and upcoming requirements before the next procurement cycle." },
      ],
    },
    areas: [
      { title: "Specification alignment", copy: "Product programs organized around approved requirements and intended applications.", details: "Translate the institution's technical and procurement requirements into a controlled item list. Record acceptable alternatives and the approval process for any change." },
      { title: "Procurement coordination", copy: "Clear product lists and ordering routines for procurement and operating teams.", details: "Define request, approval, purchase-order and receipt responsibilities. Keep ordering units and product descriptions consistent between procurement and site teams." },
      { title: "Multi-location planning", copy: "Supply coordination designed for distributed facilities and vehicle operations.", details: "Group locations by usage and delivery access. Plan distribution frequency and local holding levels so remote sites are considered in the supply cycle." },
      { title: "Demand visibility", copy: "Practical replenishment planning informed by usage patterns and operating schedules.", details: "Review historical issues, planned fleet activity and known service periods. Use the combined view to anticipate demand rather than relying only on emergency requests." },
      { title: "Program pricing", copy: "A structured basis for evaluating recurring needs, order volumes and supply arrangements.", details: "Compare expected volumes, delivery cadence, pack sizes and service requirements when reviewing a supply program. Confirm commercial terms through the institution's procurement process." },
      { title: "Supply records", copy: "Clear product and order information to support internal review and procurement workflows.", details: "Retain product identifiers, purchase orders, delivery records and approved substitutions in a consistent format for reconciliation and future planning." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=82", alt: "Institutional commercial vehicle fleet" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Vehicles coordinated across an operating fleet" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Automotive product specification support" },
      { url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=82", alt: "Vehicle maintenance coordinated for a fleet" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle included in an institutional supply program" },
      { url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=82", alt: "Supply planning for vehicles operating at scale" },
    ],
    applications: ["Public-sector fleets", "Corporate transport", "Educational institutions", "Large service networks"],
    supportTitle: "Reliable supply, clearly organized.",
    supportCopy: "We partner with institutional teams to align product choices, procurement processes and replenishment across their operation.",
    supportImage: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Vehicles moving through a connected transport network",
  },
  {
    slug: "automotive-aftermarket-distribution",
    menuLabel: "Automotive aftermarket distribution",
    title: "Automotive Aftermarket Distribution",
    eyebrow: "10 / Connecting products to demand",
    introduction: "Channel-ready product and supply support for distributors bringing automotive essentials closer to workshops and drivers.",
    heroImage: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1800&q=88",
    heroAlt: "Automobile representing the automotive aftermarket",
    overviewTitle: "A stronger link between product and point of service.",
    overview: "Aftermarket distribution depends on the right assortment, dependable availability and clear product information. NEXBLUE works with channel partners to help build a focused offer that serves local demand and supports long-term customer relationships.",
    workflow: {
      title: "Turn local demand into a channel assortment",
      introduction: "Give distributors a range and support model shaped around the workshops, retailers and fleets they actually serve.",
      steps: [
        { title: "Understand the local vehicle mix", copy: "Use customer conversations and sales history to identify common vehicle types and service needs." },
        { title: "Shape a tiered range", copy: "Separate core repeat-purchase lines from specialist products that serve a narrower set of applications." },
        { title: "Enable the counter team", copy: "Provide concise application information and a clear path for technical questions or exceptions." },
        { title: "Review sell-through", copy: "Use reorder patterns, stock-outs and customer feedback to refine the range and coverage over time." },
      ],
    },
    areas: [
      { title: "Channel assortments", copy: "Product ranges shaped around the customers, vehicle mix and services in each market.", details: "Start with the local vehicle parc and customer profile. Group fast-moving core products separately from specialist lines to keep the range useful and manageable." },
      { title: "Distributor enablement", copy: "Clear product information and partner support to help teams serve customers confidently.", details: "Equip counter and sales teams with application references, product documents and a clear route for technical questions or non-standard requests." },
      { title: "Availability planning", copy: "Supply coordination that considers demand, lead times and the distributor’s stock strategy.", details: "Use sell-through, supplier lead time and replenishment frequency when setting stock targets. Review out-of-stock and slow-moving items together." },
      { title: "Market development", copy: "Collaborative planning to identify relevant customer groups and growth opportunities.", details: "Compare current account coverage with nearby workshops, retailers and fleet operators. Prioritize segments where the range and service model answer a demonstrated need." },
      { title: "Product education", copy: "Clear application and product information to help channel teams advise customers.", details: "Keep claims tied to current technical documents and intended applications. Give partners concise product comparisons and update materials when specifications change." },
    ],
    areaImages: [
      { url: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=82", alt: "Automotive aftermarket vehicle on the road" },
      { url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82", alt: "Passenger vehicle served by aftermarket distribution" },
      { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82", alt: "Commercial vehicles in a distribution market" },
      { url: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=82", alt: "Workshop supplied through an automotive distributor" },
      { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82", alt: "Vehicle supported by aftermarket products" },
    ],
    applications: ["Regional distributors", "Automotive retailers", "Workshop suppliers", "Fleet service channels"],
    supportTitle: "Grow through a channel that knows its market.",
    supportCopy: "We work alongside distribution partners to connect relevant products, responsive supply and practical market support.",
    supportImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
    supportAlt: "Automotive aftermarket vehicle on the road",
  },
];

export function getAutomotiveSolutionPath(menuLabel) {
  const solution = automotiveSolutions.find((item) => item.menuLabel === menuLabel);
  return solution ? `/solutions/automotive/${solution.slug}` : "/#industries";
}

export function getAutomotiveOfferingSlug(title) {
  return title
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function getAutomotiveOfferingPath(solution, area) {
  return `/solutions/automotive/${solution.slug}/${getAutomotiveOfferingSlug(area.title)}`;
}